version: "3.8"

services:
  php-fpm:
    build: ./docker/phpfpm
    volumes:
      - .:/home/data/data

  nginx:
    build: ./docker/nginx
    volumes:
      - .:/home/data/data
    depends_on:
      - php-fpm

  database:
    image: percona/percona-server:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      -   db-data:/var/lib/mysql
    ports:
      - "3310:3306"
    cap_add:
      - SYS_NICE

volumes:
  db-data: