# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Configure
    _instanceof:
        Code\Shared\Bus\Event\Domain\DomainEventSubscriber:
            tags: [ 'code.domain_event_subscriber' ]

        Code\Shared\Bus\Command\Domain\CommandHandler:
            tags: [ 'code.command_handler' ]

        Code\Shared\Bus\Query\Domain\QueryHandler:
            tags: [ 'code.query_handler' ]

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Code\App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Code\:
        resource: '../../src/'
        exclude:
            - '../../src/Shared/Persistence/Infrastructure/DBAL/Migrations/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Code\App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Code\Shared\Bus\Event\Infrastructure\Symfony\InMemoryEventBus:
        arguments: [!tagged code.domain_event_subscriber]

    # Command/Query Handlers
    Code\Shared\Bus\Command\Infrastructure\Symfony\InMemoryCommandBus:
        arguments: [ !tagged code.command_handler ]

    Code\Shared\Bus\Query\Infrastructure\Symfony\InMemoryQueryBus:
        arguments: [ !tagged code.query_handler ]
