doctrine_migrations:
    migrations_paths:
        'Code\Shared\Persistence\Infrastructure\DBAL\Migrations': '%kernel.project_dir%/../src/Shared/Persistence/Infrastructure/DBAL/Migrations'
    enable_profiler: false